// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hucnlvxnwazlqukzsvdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Y25sdnhud2F6bHF1a3pzdmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTk4NjQsImV4cCI6MjA1Njk5NTg2NH0.TLVa7nRFMpbBxQsCRGtXwx-sUfKTzTLGUohyxhRp6KI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);